# -*- coding: utf-8 -*-
"""Fraud

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sQwacvJfNdQRfsK0dezhC2xdsr2I_3U
"""

#importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#loading the datasets
df = pd.read_csv('Fraud.csv')

#Exploratory Data Analysis and Data Cleaning
df.head()

df.tail()

df.shape # no. of rows and columns

df.columns # names of columns

df.info()   #for datatypes

"""7 columns are of type float64,
1 column is of type int64,
3 columns are of type object.
"""

df.isnull().sum()  #checking the missing values

# Drop rows with missing values
df = df.dropna()

# describing the data
df.describe()

from scipy.stats import zscore

# Define a function to detect outliers using Z-score
def detect_outliers_zscore(data, threshold=3):
    z_scores = zscore(data)
    return abs(z_scores) > threshold

# Detect outliers in the 'amount' column
outliers_amount = detect_outliers_zscore(df['amount'])
print(f"Outliers in 'amount': {outliers_amount.sum()}")

# Detect outliers in oldbalanceOrg
z_scores_oldbalanceOrg = zscore(df['oldbalanceOrg'])
outliers_oldbalanceOrg = abs(z_scores_oldbalanceOrg) > 3
print(f"Number of outliers in 'oldbalanceOrg': {outliers_oldbalanceOrg.sum()}")

# Detect outliers in newbalanceOrig
z_scores_newbalanceOrig = zscore(df['newbalanceOrig'])
outliers_newbalanceOrig = abs(z_scores_newbalanceOrig) > 3
print(f"Number of outliers in 'newbalanceOrig': {outliers_newbalanceOrig.sum()}")

# Drop categorical columns to avoid errors during correlation computation
df_numeric = df.drop(columns=['type', 'nameOrig', 'nameDest'])

# Compute the correlation matrix
corr_matrix = df_numeric.corr()

# Plot the correlation matrix
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm")
plt.show()

# Check for VIF (Variance Inflation Factor)
def calculate_vif(df):
    vif_data = pd.DataFrame()
    vif_data["Feature"] = df.columns
    vif_data["VIF"] = [variance_inflation_factor(df.values, i) for i in range(df.shape[1])]
    return vif_data

# Select relevant numeric features for VIF calculation
numeric_features = df[['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']]
print(calculate_vif(numeric_features))

"""**Fraud Detection Model**

We'll train a Random Forest classifier for fraud detection.
"""

# Select relevant numeric features for VIF calculation
numeric_features = df[['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']]
print(calculate_vif(numeric_features))

# Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# Define features and target variable
X = df[['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'type']]
y = df['isFraud']

# Convert categorical 'type' to numeric using One-Hot Encoding
X = pd.get_dummies(X, columns=['type'], drop_first=True)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# # Train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# # Predict on test data
y_pred = rf_model.predict(X_test)

"""Evaluating Model Performance"""

# Confusion matrix and classification report
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# AUC-ROC Score
y_pred_proba = rf_model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(f"AUC-ROC Score: {roc_auc}")

"""Feature Importance"""

# Get feature importances from the Random Forest model
importances = rf_model.feature_importances_
feature_names = X.columns

# Create a DataFrame to display feature importance
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
print("Feature Importance:\n", feature_importance_df)

"""Measuring Effectiveness"""

# After model improvements, check if model performance has improved
# Assuming you have an updated test dataset
updated_y_pred = rf_model.predict(X_test)

print("Updated Confusion Matrix:\n", confusion_matrix(y_test, updated_y_pred))
print("\nUpdated Classification Report:\n", classification_report(y_test, updated_y_pred))

"""***Answers to task questions***

1. **Data cleaning (Missing values, outliers, and multi-collinearity)**
Answer: The code includes steps for:
Missing values: Checking and handling missing values.
Outliers: Detecting outliers in numerical columns using Z-score.
Multi-collinearity: Checking for multi-collinearity using a correlation matrix and calculating VIF.
2. **Describe your fraud detection model in elaboration**
Answer: The model used is a Random Forest classifier, which is described briefly as a supervised machine learning algorithm known for handling class imbalance and non-linear relationships. The code includes the steps for training and evaluating this model.
3. **How did you select variables to be included in the model?**
Answer: The variables were selected based on domain knowledge (e.g., amount, oldbalanceOrg, newbalanceOrig) and were further refined through feature importance ranking from the Random Forest model. Additionally, categorical variables like type were encoded using one-hot encoding.
4. **Demonstrate the performance of the model by using the best set of tools**
Answer: The performance of the model is demonstrated using tools such as:
Confusion matrix: To evaluate true positives, false positives, etc.
Classification report: To assess precision, recall, F1-score.
AUC-ROC score: To evaluate the model’s ability to distinguish between fraud and non-fraud transactions.
5. **What are the key factors that predict fraudulent customers?**
Answer: The feature importance output from the Random Forest model is used to identify key factors such as amount, oldbalanceOrg, newbalanceOrig, and type of transaction. The most predictive features are ranked based on their importance in the model.
6. **Do these factors make sense? If yes, how? If not, how not?**
Answer: The factors identified in the feature importance ranking make sense:
Amount: Fraudulent transactions often involve abnormally high or low amounts.
Transaction type: Fraud tends to occur in specific types of transactions (e.g., transfers or cash outs).
Balance differences: Sudden large changes in balances could signal fraud.
7. **What kind of prevention should be adopted while the company updates its infrastructure?**
Answer: Recommendations for infrastructure updates include:
Real-time monitoring: To flag suspicious activities instantly.
Two-factor authentication: To secure high-risk transactions.
Transaction limits: To prevent large, rapid transfers that may be fraudulent.
Data encryption: To ensure secure transactions.
8. **Assuming these actions have been implemented, how would you determine if they work?**
Answer: To measure the effectiveness of these actions:
Monitor fraud rates: Before and after implementation.
Evaluate model performance: Using confusion matrices and classification reports after implementing infrastructure changes to check for improvements.
Customer feedback and audits: Ensure customers are satisfied with the security changes, and conduct regular audits to assess system effectiveness.
"""